### ISSUE TITLE
Cursor update error

### ISSUE THREAD

**Issue by fabcard** [farag2/Utilities#11]
Hello @farag2 
Hope you're doing well.
So after the today's update on cursor dark.zip, when I run the installer script I get error messages as you can see on screenshot.
![error](https://user-images.githubusercontent.com/88634350/196055091-f1410603-8c89-4ce9-9e0c-d5307e967344.jpg)
Thanks in advance.

**Comment by farag2** [comment]
Hm... Will check very soon

**Comment by farag2** [comment]
It seems after re-uploading the error is gone. At least I didn't face it on my PC.
