### ISSUE TITLE
Firefox_Setup.exe.ps1

### ISSUE THREAD

**Issue by Hellements** [farag2/Utilities#4]
Hello,
So I'm having a problem trying to install Firefox using your Firefox_Setup.exe.ps1 script as you can see on the picture. It won't be installed.
![error](https://user-images.githubusercontent.com/88634350/130900987-461c57b8-ecac-4f68-87f5-991e3dbedcdb.jpg)
It's a fresh installation of Win10Pro (original) with all latest updates installed and has your Sophia Script too (default settings).
Thank you so much.

EDIT:
Tried to run script again after running Internet Explorer 11 for the first time and got this error now:
![error2](https://user-images.githubusercontent.com/88634350/130913989-cd26145c-4544-4fbd-b3fc-e9a6f897c9bb.jpg)
What happens if I decide to remove IE11 using Sophia and then Firefox_Setup.exe.ps1, will it never work? We must have IE11?
Thanks in advance.

**Comment by farag2** [comment]
I think, I've fixed it. :)
