### ISSUE TITLE
Acrobat_Reader_DC.ps1

### ISSUE THREAD

**Issue by Hellements** [farag2/Utilities#5]
Hi,
So I'm having a problem trying to install Acrobat Reader using your Acrobat_Reader_DC.ps1 script as you can see on the picture. It won't be installed.
![error](https://user-images.githubusercontent.com/88634350/130900070-7dc6db04-109e-4e09-8887-3403ff0339aa.jpg)
It's a fresh installation of Win10Pro (original) with all latest updates installed and has your Sophia Script too (default settings).
Thank you so much.

**Comment by farag2** [comment]
I saw it. I'll take a look only in Sunday or Monday.

**Comment by Hellements** [comment]
Ok friend. I'm really sorry for bothering you.
Don't need to hurry, please.
Have a great weekend.

**Comment by farag2** [comment]
👯‍♀️

**Comment by farag2** [comment]
Just don;t pay attention: I figured out, that Adobe dosn't place Language.cab to en_US version installer. :)
