### ISSUE TITLE
Acrobat_Reader_DC_x64.ps1 error.

### ISSUE THREAD

**Issue by Hellements** [farag2/Utilities#6]
Hello @farag2 , I hope you are doing great.
So today I tried to download the new Reader x64 using your "Acrobat_Reader_DC_x64.ps1" script, and it is showing the following error:
![error](https://user-images.githubusercontent.com/88634350/133304898-d94f6bda-1e09-4c75-9737-d4179f3d5759.jpg)
That is strange because it was working on the previous Reader version.
Sorry for bothering you so much. I really like your scripts and work you're doing here.
Again, thank you.

**Comment by farag2** [comment]
Hm... As I may see your culture is en_US. Am I right?

**Comment by farag2** [comment]
Actually, I get the valid url. But I don't know why it looks like for you like a "ladder" :)

**Comment by farag2** [comment]
Fixed. `.Trim()`. Please, test again)
