### ISSUE TITLE
Acrobat_Reader_DC_x64.ps1 error.

### ISSUE THREAD

**Issue by Hellements** [farag2/Utilities#7]
Hello again, @farag2 
Sorry for bothering you.
I'm trying to download the newest Reader DC x64 using the script, and it's giving me this error:
![error](https://user-images.githubusercontent.com/88634350/135347319-33d0351b-81e1-4d78-99d6-640ddc64dd50.jpg)
If I'm not wrong, this happened last time when I was trying to download an upgraded version too.
Thank you!

**Comment by farag2** [comment]
Hm...

**Comment by farag2** [comment]
Ah, the same problem with Adobe:

I get the latest Reader x64 (and Acrobat Pro DC, due to that they're equal and share the same codebase) via `https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/reader/current_version.txt`

And Adobe again outputs the wrong version for Reader...

**Comment by farag2** [comment]
`https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720095/AcroRdrDCx642100720095_en_US.exe`

**Comment by farag2** [comment]
Finally, I've overcome the URL parsing!

**Comment by farag2** [comment]
Please, check <https://github.com/farag2/Utilities/blob/master/Download/Acrobat_Reader_DC_x64.ps1>
