### ISSUE TITLE
TaskbarX.ps1 issue.

### ISSUE THREAD

**Issue by Hellements** [farag2/Utilities#8]
Hi, @farag2 . I hope you are doing good.
It's me again... sorry.
I'm trying to update my TaskbarX with a new version using your script and this message appears:
![error](https://user-images.githubusercontent.com/88634350/135537414-2deb3f19-b7c3-487e-8786-1c519899df48.jpg)
I believe it's happening because the program is already running and can't be replaced.
Thank you, friend. I really appreciate your work.

**Comment by farag2** [comment]
Of course. I'll update tomorrow. And I also need to figure out how to vet the always valid URL for Reader...

**Comment by Hellements** [comment]
Please, don't need to rush, friend. Take your time.
Thank you a lot.

**Comment by farag2** [comment]
Fixed!
