### ISSUE TITLE
Market value seems to be incorrect for Search-MSStore functions

### ISSUE THREAD

**Issue by SweetestSufferance** [farag2/Utilities#9]
https://github.com/farag2/Utilities/blob/3818b80710bbc8e9cf4e53581c7a2f4aec634f61/Search_UWP_Package_in_Store.ps1#L29
https://github.com/farag2/Utilities/blob/3818b80710bbc8e9cf4e53581c7a2f4aec634f61/Search_UWP_Package_in_Store.ps1#L89

Here is the error:
```
Invoke-WebRequest : {"code":"InvalidParameterValue","data":[],"details":[],"innererror":{"code":"InvalidParameterValue","data":[],"details":[] 
,"message":"Parameter market was specified with invalid value: en.","source":"StoreEdgeFD","target":"market"},"message":"Parameter market was  
specified with invalid value: en.","source":"StoreEdgeFD","target":"market"}
At line:38 char:7
+     ((Invoke-WebRequest -UseBasicParsing -Uri ($Base + $Parameters)). ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
Fixed the issue by changing the line to this.  Probably not the best, but seems to work at the moment.
`market         = (Get-UICulture).Name.split("-")[1]`

Thanks for creating this function, it's a huge help at the moment.

**Comment by farag2** [comment]
Hi. It's not my code. I just found it. Do not know how it works. I use another method to download the package I need: https://github.com/farag2/Sophia-Script-for-Windows/blob/ad1327eba0a0f17fe76d00232f3740be3680462a/Sophia%20Script/Sophia%20Script%20for%20Windows%2011/Module/Sophia.psm1#L9145

**Comment by SweetestSufferance** [comment]
Thanks again!
